# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/aderemifayoyiwa/opt/anaconda3/envs/virtual_env/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/aderemifayoyiwa/opt/anaconda3/envs/virtual_env/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/aderemifayoyiwa/opt/anaconda3/envs/virtual_env/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/aderemifayoyiwa/opt/anaconda3/envs/virtual_env/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/aderemifayoyiwa/opt/anaconda3/envs/virtual_env/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/aderemifayoyiwa/opt/anaconda3/envs/virtual_env/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/aderemifayoyiwa/opt/anaconda3/envs/virtual_env/lib']


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
vector = np.ones(10)
print(vector)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### 4.  How to find the memory size of any array (★☆☆)

In [4]:
n = np.array([1, 2, 3, 4, 5])
print(n.size)
print(n.itemsize)
print("memory size of n: ", n.size * n.itemsize)

5
8
memory size of n:  40


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
python -c "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (<ipython-input-5-1663cd30cb7c>, line 1)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
a = np.arange (10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [8]:
a = np.arange(10)
print(a)
b = a[::-1]
print(b)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [10]:
non_zero = np.nonzero([1, 2, 0, 0, 4, 0])
print(non_zero)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
a = np.random.random((3,3,3))
print(a)

[[[0.19409851 0.80140688 0.05557576]
  [0.71081543 0.36304809 0.46770831]
  [0.10938178 0.1041948  0.8739298 ]]

 [[0.66407056 0.35115731 0.87742078]
  [0.04967941 0.99678412 0.95606572]
  [0.38459162 0.04778586 0.25212729]]

 [[0.50668629 0.80442821 0.49301552]
  [0.91335087 0.7900108  0.70494564]
  [0.93983631 0.01080298 0.64289013]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
a = np.random.random((10,10))
#print(a)
a_min, a_max = a.min(), a.max()
print(a_min, a_max)

0.01041196272469569 0.9982015889563203


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
a = np.random.random(30)
mean_value = a.mean()
print(mean_value)

0.4911773852342034


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
a = np.ones((8,8))
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
a = np.ones((8,8))
print(a)
b = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(b)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
a = np.diag(1+np.arange(4), k= -1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
a = np.zeros((8,8), dtype=int)
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
print(np.unravel_index(99, (6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
a = np.array([[0,1], [1,0]])
b = np.tile(a,(4,4))
print(b)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
a = np.random.random((5,5))
a_min, a_max = a.min(), a.max()
b= a - a_min
c = a_max - a_min
d = b/c
print(d)

[[0.         0.16769137 0.78076915 0.01557622 0.68311843]
 [0.08759796 0.59778014 0.63459656 0.42175914 0.59462848]
 [0.79579737 0.0531201  0.18961619 0.08000545 0.24338669]
 [0.93350711 1.         0.42077396 0.14811707 0.75485117]
 [0.78370288 0.98502267 0.9845622  0.86005284 0.53726626]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
color = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-23-9c1e4f7d6645>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
a = np.dot(np.ones((5,3)), np.ones((3,2)))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
a = np.arange(16)
a[(3 < a) & (a < 8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14 15]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [43]:
z = 3
#z ** z (legal)
#2 << z >> 2 (legal)
#z <- z 
#lj*z (legal)
#z/1/1(legal)
#z<z>z

4

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [27]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-27-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-27-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
a = np.random.uniform(-10,+10,10)
b = np.copysign(np.ceil(np.abs(a)),a)
print(b)

[ 4. -3.  7. -4. -9.  3.  7. -3. -9. -6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [29]:
a = np.random.randint(0,10,5)
b = np.random.randint(0,10,5) 
c = np.intersect1d(a,b)
print(c)

[1 5 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
defaults = np.setter(all="ignore")
a = np.ones(1)/0

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [31]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-31-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [46]:
today = np.datetime64('today','D')
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print(yesterday)
print(today)
print(tomorrow)

2021-01-02
2021-01-03
2021-01-04


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [47]:
dates = np.arange('2016-07', '2016-08', dtype = 'datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [62]:
A = np.ones(3) 
B = np.ones(3)*2
C = np.ones(3)*3

addition = np.add(A,B,out=B)
division = np.divide(A,2,out=A)
neg = np.negative(A,out=A)
#multiplication = (A,B,out=A)

compute = addition * (neg/division)
print(compute)

[3. 3. 3.]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [69]:
a = np.random.uniform(0,5,5)

print(np.floor(a))
print(np.trunc(a))
print(a - a%1)
print(np.ceil(a)-1)
print(a.astype(int))

[0. 3. 3. 0. 3.]
[0. 3. 3. 0. 3.]
[0. 3. 3. 0. 3.]
[0. 3. 3. 0. 3.]
[0 3 3 0 3]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [74]:
a = np.zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [76]:
def generate():
    for i in range(10):
        yield i
a = np.fromiter(generate(),dtype=float,count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [77]:
a = linspace(0,1,11,endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [80]:
a = np.random.random(10)
a.sort()
print(a)

[0.06588741 0.14781444 0.1523147  0.32565088 0.45836699 0.46236173
 0.48878857 0.57741541 0.81004262 0.85213431]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [82]:
a = np.arange(5)
b = np.add.reduce(a)
print(b)

10


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [84]:
A = np.random.randint(0,10,10)
B = np.random.randint(0,10,10) 

comparison = np.array_equal(A,B)
print(comparison)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [94]:
a = np.ones(5)
a.flags.writeable=False
a[3] = 8 
print(a)

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [96]:
a = np.random.random((5,2))
b,c = a[:,0], a[:,1]
d = np.sqrt(b**2+c**2)
e = np.arctan2(c,b)
print(d)
print(e)

[0.96966528 0.91550261 0.25067148 0.4588703  0.38008909]
[1.37424852 0.15138313 0.530989   1.30301752 0.54022818]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [99]:
a = np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.05712218 0.         0.30705278 0.1045834  0.39602889 0.09842271
 0.13451572 0.4175391  0.65145467 0.557894  ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [100]:
a = np.zeros((5,5), [('x',float), ('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),
                            np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [101]:
X = np.arange(10)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X,Y)
print(np.linalg.det(C))

33961.93294480225


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [102]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [108]:
np.set_printoptions(threshold=np.nan)
a = np.zeros((16,16)) 
print(a) 

ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [109]:
a = np.arange(50)
b = np.random.uniform(0,100)
index = (np.abs(a-b)).argmin()
print(a[index])

41


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [111]:
a = np.zeros(10, [('position',[('x', float, 1),
                               ('y', float, 1)]),
                  ('color',   [('r', float, 1),
                               ('g', float, 1),
                               ('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-111-63ae7ae9929c>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(10, [('position',[('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [112]:
a = np.random.random((10,2))
b,c = np.atleast_2d(a[:,0], a[:,1])
e = np.sqrt((b-b.T)**2 + (c-c.T)**2)
print(e)

[[0.         0.51379133 0.28701638 0.18956429 0.33818254 0.2932356
  0.25013802 0.66683981 0.58847717 0.64284586]
 [0.51379133 0.         0.45487903 0.39033815 0.82069543 0.5620678
  0.54935435 0.19243838 0.31591632 0.15724963]
 [0.28701638 0.45487903 0.         0.37675051 0.4294744  0.10953683
  0.51414401 0.53176702 0.67336488 0.52212227]
 [0.18956429 0.39033815 0.37675051 0.         0.52627931 0.42955996
  0.1730852  0.57064806 0.40186039 0.54002391]
 [0.33818254 0.82069543 0.4294744  0.52627931 0.         0.33971489
  0.52880929 0.94199897 0.92664918 0.92557294]
 [0.2932356  0.5620678  0.10953683 0.42955996 0.33971489 0.
  0.54040789 0.64054024 0.76367105 0.63148619]
 [0.25013802 0.54935435 0.51414401 0.1730852  0.52880929 0.54040789
  0.         0.73593123 0.47733806 0.70363976]
 [0.66683981 0.19243838 0.53176702 0.57064806 0.94199897 0.64054024
  0.73593123 0.         0.47436627 0.03705711]
 [0.58847717 0.31591632 0.67336488 0.40186039 0.92664918 0.76367105
  0.47733806 0.4743662

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [113]:
a = (np.random.rand(10)*100).astype(np.float32)
b = a.view(np.int32)
b[:] = a
print(b)

[64 14 69  6 55 28 36 45 17 87]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [123]:
a = ('''1, 2, 3, 4, 5
        6,  ,  , 7, 8
        ,  , 9,10,11
''')
b = np.genfromtxt(a, delimiter=",")
print(b)

OSError: 1, 2, 3, 4, 5
        6,  ,  , 7, 8
        ,  , 9,10,11
 not found.

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [124]:
a = np.arange(16).reshape(4,4)
for index, value in np.ndenumerate(a):
    print(index,value)
for index in np.ndindex(a.shape):
    print(index, a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11
(3, 0) 12
(3, 1) 13
(3, 2) 14
(3, 3) 15
(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11
(3, 0) 12
(3, 1) 13
(3, 2) 14
(3, 3) 15


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [125]:
a, b = np.meshgrid(np.linspace(-1,1,10), np.linspace(-10,1,10))
c = np.sqrt(a*a+b*b)
sigma, mu = 1.0, 0.0
d = np.exp(-((c-mu)**2)/(2.0*sigma**2.0))
print(d)

[[1.16984592e-22 1.42532935e-22 1.65293262e-22 1.82451918e-22
  1.91688066e-22 1.91688066e-22 1.82451918e-22 1.65293262e-22
  1.42532935e-22 1.16984592e-22]
 [1.12665743e-17 1.37270890e-17 1.59190949e-17 1.75716140e-17
  1.84611307e-17 1.84611307e-17 1.75716140e-17 1.59190949e-17
  1.37270890e-17 1.12665743e-17]
 [2.43609496e-13 2.96811537e-13 3.44207795e-13 3.79939095e-13
  3.99172510e-13 3.99172510e-13 3.79939095e-13 3.44207795e-13
  2.96811537e-13 2.43609496e-13]
 [1.18259394e-09 1.44086142e-09 1.67094493e-09 1.84440130e-09
  1.93776925e-09 1.93776925e-09 1.84440130e-09 1.67094493e-09
  1.44086142e-09 1.18259394e-09]
 [1.28889101e-06 1.57037277e-06 1.82113726e-06 2.01018470e-06
  2.11194500e-06 2.11194500e-06 2.01018470e-06 1.82113726e-06
  1.57037277e-06 1.28889101e-06]
 [3.15381231e-04 3.84257549e-04 4.45617596e-04 4.91875978e-04
  5.16775903e-04 5.16775903e-04 4.91875978e-04 4.45617596e-04
  3.84257549e-04 3.15381231e-04]
 [1.73258520e-02 2.11096565e-02 2.44805454e-02 2.70218060e

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [131]:
n = 10 
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z) 

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [132]:
a = np.random.rand(5,10)
b = a - a.mean(axis=1, keepdims=True)
print(b)

[[-0.12065381  0.13276847  0.07098132 -0.1661213  -0.10335594  0.18942277
   0.35685664  0.18828527 -0.30260981 -0.24557362]
 [-0.21437359  0.41018667  0.00263765 -0.14252274 -0.15091057  0.30539931
  -0.00833012  0.50320664 -0.321894   -0.38339925]
 [-0.1364145  -0.12552883  0.02651199  0.42380328  0.30316759 -0.26575906
   0.24976668 -0.31810647  0.07859958 -0.23604026]
 [ 0.31895199 -0.18373345  0.2349156   0.28675093 -0.25066015 -0.60971273
  -0.03582601  0.157499   -0.09641723  0.17823204]
 [ 0.18186003 -0.23572491  0.01761496  0.09679221  0.2320484  -0.15954437
  -0.22362092 -0.25104457 -0.17286763  0.51448679]]


#### 59. How to sort an array by the nth column? (★★☆)

In [134]:
a = np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[9 1 9]
 [2 3 0]
 [4 2 9]]
[[9 1 9]
 [4 2 9]
 [2 3 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [135]:
a = np.random.randint(0,3,(3,10))
print((~a.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)