## Linear Algebra Quiz #3

![title](./img/3_0.jpeg)

We strongly suggest working with numpy :)

In [1]:
#Do your imports here
import numpy as np

![title](./img/3_2.png)
Create a program that can output

- What is the value of element c23​ of Matrix C where C=A x B ?
- What is the value of element c23​ of Matrix C where C=B x A ?

In [21]:
#convert A and B into arrays
A = np.array([[3, 1, 2], [-5, 4, 1], [0, 3, -8]])
B = np.array([[0, 5, -1], [3, 2, -1], [10, 0.5, 4]])

#Find the product of A and B
C = np.multiply (A,B)
print("Matrix C is:" )
print(C)

#printing the element in row 2, column try of the result of matrix multiplication
a = C[1][2]
print("element in row 2, column 3 of matrix C is", a)

#multiplication of matrix B and matrix A
D = np.multiply(B,A)
print("Matrix D is:")
print(D) 

#printing the element in row 2, column try of the result of matrix multiplication
e = D[1][2]
print("element in row 2, column 3 of matrix C is", e)

Matrix C is:
[[  0.    5.   -2. ]
 [-15.    8.   -1. ]
 [  0.    1.5 -32. ]]
element in row 2, column 3 of matrix C is -1.0
Matrix D is:
[[  0.    5.   -2. ]
 [-15.    8.   -1. ]
 [  0.    1.5 -32. ]]
element in row 2, column 3 of matrix C is -1.0


In [40]:
# okay numpy is great but... how would you inverse a matrix by hand?

def inverse_matrix(A):
#Inserting my 2 x 2 matrix ([a,b], [c,d])
    A = np.array([[4,7], [2,6]])

#Getting the values of diagonal multiplication a*d and b*c
    d1 = (A[0][0]) * (A[1][1])
    d2 = (A[0][1]) * (A[1][0])

#Subtracting the left diagonal multiplication from the right (ad - bc)
    mult = 1 / (d1 - d2)
    
#Exchanging a and d and negating b and c    
    a = A[1][1] 
    b = (A[0][1])*(-1)
    c = (A[1][0])*(-1) 
    d = A[0][0]
    
#Converting the new a,b,c,d values into an array    
    B = np.array([[a,b],[c,d]])
    
#Finally calculating the inverse of the original matrix by multiply 'mult' by the new matrix B    
    C = mult * B
    return C
inverse_matrix(A)


array([[ 0.6, -0.7],
       [-0.2,  0.4]])

![title](./img/3_1.png)
Create a program that can output

- What is the value of the ijth element if i = 2 and j=3?
- What is the value of the ijth element if i = 3 and j=1?

In [42]:
#Creating matrices A, B and C
A = np.array([[3, 0.6, 4, -3], [-1.3, 4, 0, 8.6], [7, 0, -8, 0.006]])
B = np.array ([[3, -5.76, 45, 0], [2, -2, 1.3, 9], [-9, 0, 0, 0]])
C = np.array([[0, 1009, -66.7849, 90], [0, 5, 4, -0.07], [-7.7, 0, 0, 0]])

#Generating matrix D
D = A + B - C
print(D)

[[ 6.000000e+00 -1.014160e+03  1.157849e+02 -9.300000e+01]
 [ 7.000000e-01 -3.000000e+00 -2.700000e+00  1.767000e+01]
 [ 5.700000e+00  0.000000e+00 -8.000000e+00  6.000000e-03]]


In [46]:
D[1][2]

-2.7

In [47]:
D[2][0]

5.7

In [ ]:
# Just answer using code --> easy stuff!

# Harder
# Can you build a matrix solver that can do output the result given n matrices and a sequence of operations such as [add subtract multiply transpose?]
#Some ideas on valid operations: Multiplication Addition Subtraction Inverstion Transposed. 

![title](./img/3_3.png)
Create a program that can output
- How many rows will C have?
- How many columns will C have?
- What will be the value of c13​?

In [55]:
print("Matrix C which is the product of matrices A and B will be a row vector with three columns")

Matrix C which is the product of matrices A and B will be a row vector with three columns


In [54]:
#Getting matrices
A = np.array([0.6, -15, 2, 5, 98])
B = np.array([[2, 2, -4], [9, -14, 0], [13, -0.5, 44], [1, 9, 4], [0, 0, 5]])

#Generating the transpose of A
A_T = A.T

#Dot product of transpose of matrix A and matrix B
C = np.dot(A_T, B)
print(C)

#Value of C13 
C[2]

[-102.8  255.2  595.6]


595.6